flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- commonmark-0.2.6
- commonmark-extensions-0.2.5.4
- commonmark-pandoc-0.2.2.1
- hslua-module-zip-1.1.3
- pandoc-lua-marshal-0.2.7
- tls-2.0.5
- skylighting-format-blaze-html-0.1.1.2
- skylighting-core-0.14.1.2
- skylighting-0.14.1.2
- zip-archive-0.4.3.2
- toml-parser-2.0.0.0
- typst-symbols-0.1.6
- texmath-0.12.8.9
- git: https://github.com/jgm/typst-hs
  commit: dfe0367b248419c3555044705fa79a52b9c20089
- git: https://github.com/jgm/djoths
  commit: 7f912e3ee593a86e3d179e8f3e1898a93171fb99
- git: https://github.com/jgm/citeproc
  commit: 76f7f134f3ba7c0aebe84d4f24c424021da3844e

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.11
nix:
  packages:
  - pkg-config
  - zlib
