flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- commonmark-0.2.5.1
- commonmark-extensions-0.2.5.2
- commonmark-pandoc-0.2.2.1
- typst-0.5.0.1
- tls-2.0.1
- git: https://github.com/jgm/djoths
  commit: 970390f4e8d1650378c826d293482ddf710c58a9
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.11
nix:
  packages:
  - pkg-config
  - zlib
