flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- tls-2.1.0
- crypton-connection-0.4.1
- toml-parser-2.0.1.0
- skylighting-core-0.14.3
- skylighting-0.14.3
- doclayout-0.5
- doctemplates-0.11.0.1
- hslua-module-doclayout-1.2.0
- djot-0.1.2.2
- commonmark-0.2.6.1
- commonmark-pandoc-0.2.2.2
- typst-symbols-0.1.7
- git: https://github.com/jgm/texmath.git
  commit: 9539ea28538dc633001260cc8a08fb3aaeca5775
- git: https://github.com/jgm/typst-hs.git
  commit: 6b9b52ffc2ca6309a8a8ac18e7ca3f4f66cdfdd3
- git: https://github.com/pandoc/pandoc-lua-marshal
  commit: 2dc58d431bb3e4d55999db03c470fbf32970b3d5
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.33
nix:
  packages:
  - pkg-config
  - zlib
