flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12
- skylighting-0.12
- doctemplates-0.10
- git: https://github.com/jgm/texmath.git
  commit: 19700530733707284bb41f24add757f19ca23430
- git: https://github.com/jgm/citeproc.git
  commit: b27201c3ac48ffd2853f77152df19b6e2cf36987
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]


