flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- commonmark-0.2.6
- commonmark-extensions-0.2.5.4
- commonmark-pandoc-0.2.2.1
- pandoc-lua-marshal-0.2.6
- tls-2.0.1
- skylighting-format-blaze-html-0.1.1.2
- skylighting-core-0.14.1.1
- skylighting-0.14.1.1
- djot-0.1.1.3
- zip-archive-0.4.3.1
- toml-parser-2.0.0.0
- typst-symbols-0.1.6
- git: https://github.com/jgm/typst-hs
  commit: 926d1c60c80cc9f205e31b7f070835665c2817dd
- git: https://github.com/jgm/texmath
  commit: 66e747472d87b2379f4224dd8efb5950e3aef966

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.11
nix:
  packages:
  - pkg-config
  - zlib
