flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- hslua-2.4.0
- hslua-module-doclayout-1.2.0.1
- hslua-module-system-1.2.3
- hslua-objectorientation-2.4.0
- hslua-packaging-2.3.2
- pandoc-lua-marshal-0.3.1
- tls-2.1.7
- skylighting-core-0.14.6
- skylighting-0.14.6
- skylighting-format-typst-0.1
- typst-symbols-0.1.8.1
- doclayout-0.5.0.1
- citeproc-0.10
- texmath-0.13
- typst-0.8.0.2
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-23.22
nix:
  packages:
  - pkg-config
  - zlib
