flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
packages:
- '.'
extra-deps:
- pandoc-types-1.22
- rfc5051-0.2
- haddock-library-1.9.0
- skylighting-0.10.2
- skylighting-core-0.10.2
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- HsYAML-aeson-0.2.0.0
- commonmark-0.1.1.3
- commonmark-extensions-0.2.0.4
- commonmark-pandoc-0.2.0.1
- doctemplates-0.9
- texmath-0.12.1
- citeproc-0.3.0.5
# - citeproc:
#   git: https://github.com/jgm/citeproc.git
#   commit: d44e24696ab444090d0e63e321c3a573f68b2e74
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-16.23
nix:
  packages: [zlib]
