flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- tls-2.1.0
- crypton-connection-0.4.1
- toml-parser-2.0.1.0
- typst-symbols-0.1.6
- skylighting-core-0.14.3
- skylighting-0.14.3
- doclayout-0.5
- doctemplates-0.11.0.1
- texmath-0.12.8.10
- typst-0.6
# even though the resolver has this version, we need the Hackage revision:
- hslua-module-doclayout-1.1.1.2
- git: https://github.com/jgm/commonmark-hs
  subdirs: [commonmark]
  commit: ff9fe5736d2b8eb65e148e9c4a2a95b3d96eefd6
- git: https://github.com/jgm/djoths
  commit: 1da0c094a4bdfd67ce195b1c338075a6dcd1f3a4

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.33
nix:
  packages:
  - pkg-config
  - zlib
