flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- commonmark-0.2.6
- commonmark-extensions-0.2.5.4
- commonmark-pandoc-0.2.2.1
- hslua-module-zip-1.1.3
- pandoc-lua-marshal-0.2.7
- tls-2.0.2
- skylighting-format-blaze-html-0.1.1.2
- skylighting-core-0.14.1.1
- skylighting-0.14.1.1
- zip-archive-0.4.3.1
- toml-parser-2.0.0.0
- typst-symbols-0.1.6
- typst-0.5.0.3
- git: https://github.com/jgm/texmath
  commit: 64e1cbf1fdbe19382804be487cc49bdcea2ac799
- git: https://github.com/jgm/djoths
  commit: 52882f88e4904eabc940e635595dad1008064be0

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.11
nix:
  packages:
  - pkg-config
  - zlib
