flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- tls-2.1.0
- toml-parser-2.0.1.0
- typst-symbols-0.1.6
- texmath-0.12.8.9
- emojis-0.1.4.1
- commonmark-extensions-0.2.5.5
- skylighting-core-0.14.2
- skylighting-0.14.2
- citeproc-0.8.1.1
- djot-0.1.2.1
- typst-0.5.0.5

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.24
nix:
  packages:
  - pkg-config
  - zlib
