flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- tls-2.1.0
- crypton-connection-0.4.1
- toml-parser-2.0.1.0
- typst-symbols-0.1.6
- skylighting-core-0.14.3
- skylighting-0.14.3
- doclayout-0.5
- doctemplates-0.11.0.1
- typst-0.6
- hslua-module-doclayout-1.2.0
- pandoc-lua-marshal-0.2.9
- djot-0.1.2.2
- texmath-0.12.8.11
- commonmark-0.2.6.1
- commonmark-pandoc-0.2.2.2

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.33
nix:
  packages:
  - pkg-config
  - zlib
