flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- commonmark-0.2.1
- commonmark-pandoc-0.2.1.1
- skylighting-core-0.11
- skylighting-0.11
- doctemplates-0.10
- citeproc-0.4.1
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.0
nix:
  packages: [zlib]
