flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- tls-2.1.0
- crypton-connection-0.4.1
- toml-parser-2.0.1.0
- typst-symbols-0.1.6
- skylighting-core-0.14.3
- skylighting-0.14.3
- doclayout-0.5
- doctemplates-0.11.0.1
- texmath-0.12.8.10
- typst-0.6
- hslua-module-doclayout-1.2.0
- pandoc-lua-marshal-0.2.8
- git: https://github.com/jgm/commonmark-hs
  subdirs: [commonmark, commonmark-pandoc]
  commit: 7130ce27089b47588f64946263defc05fd72ab29
- git: https://github.com/jgm/djoths
  commit: 8582cdc763716489f5d0f7f5cd250199adcccd17

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.33
nix:
  packages:
  - pkg-config
  - zlib
